### PR TITLE
Modified the UI

### LINKED ISSUE #1: Increase the height of the links
Asslamualaikum!

I feel the height of the links rectangles can be increased. Also in mobile devices the width is a bit small, it can be increased.

If you don't mind, I would love to work on this issue and make the PR. Thank you

image

image

### PR DESCRIPTION
**Pull request by mohammadshaad**
## Issue Resolved
Closes #1 

I have did the required changes as well as modified the UI a little bit so that it looks more appealing. 

## Screenshot for Desktop Version
image

## Screenshot for the mobile version 
image

### CODE REVIEW

**Comment by mohammadshaad** [comment]
@MahekUnnisa kindly review and merge the PR

**Review by MahekUnnisa — APPROVED** [review]
Looks great.

**Comment by MahekUnnisa** [comment]
Thanks @mohammadshaad

**Comment by mohammadshaad** [comment]
I guess you are not following me back 😂

**Pull request merged**
